### ISSUE TITLE
求助模板问题

### ISSUE THREAD

**Issue by fantasticsoul** [sherlockwang/cra-template-jw-mst#1]
已通过谷歌解决

**Comment by fantasticsoul** [comment]
因为我也加了一个cra-template
https://github.com/concentjs/cra-template-concent-ts
尝试合并到fb主干，流水线报错
https://github.com/facebook/create-react-app/pull/10241
看错误是缺一个babel包，有点晕头了

**Comment by sherlockwang** [comment]
靠npm包，cra-template-jw-mst是包名，你不需要去clone这个模版的项目

Best regards,
Jinghan Wang
